packages:
  - packages/*
  - packages/config/*
  - packages/tools/*
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  cookie@<0.7.0: '>=0.7.0'
